config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  constraints PathAnalysis.new do
    get "(*page_path)/add", to: "pages#new", as: "pages"
    post "(*page_path)/add", to: "pages#create"
    patch "*page_path/edit", to: "pages#update", as: "page_edit"
    get "*page_path/edit", to: "pages#edit"
    get "*page_path", to: "pages#show", as: "page"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  has_ancestry

  validates :name, presence: true, uniqueness: true, format: { with: /\A[\wа-яА-Я]+\z/ }
  validates :title, presence: true
  validates :content, presence: true

  def hash_tree
    subtree.arrange
  end

  def build_name
    Page.where(id: path_ids).pluck(:name).join('/')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page, only: %i[show edit update]
  before_action :session_ancestor, only: %i[new edit]

  def index
    @root = Page.all.roots
  end

  def show; end

  def new
    @page = Page.new
  end

  def create
    @page = session[:ancestor].nil? ? Page.new(page_param) : ancestor.children.create(page_param)
    if @page.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @page.update(page_param)
    if @page.save
      redirect_to page_path
    else
      render :edit
    end
  end

  private

  def page_param
    params.require(:page).permit(:name, :title, :content)
  end

  def find_page
    @page = Page.find_by(name: explore_page)
  end

  def session_ancestor
    session[:ancestor] = explore_page
  end

  def ancestor
    Page.find_by(name: session[:ancestor])
  end

  def explore_page
    PathAnalysis.new.explore_path(request)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def render_tree(root_page)
    @tree = []
    root_page.map do |page|
      if page.has_children?
        child_tree(page.hash_tree)
      else
        @tree << "<br>"
        @tree << link_to(page.name, page.name)
      end
    end
    sanitize @tree.join
  end

  def child_tree(hashtree, indent = 0)
    hashtree.map do |ancestor, child|
      @tree << "&nbsp;" * indent
      @tree << link_to(ancestor.name, ancestor.build_name)
      @tree << "<br>"
      child_tree(child, indent + 2) if child.is_a?(Hash) && !child.empty?
    end
  end

  def normalizing_content(text)
    text.gsub!(/\*\[([\wа-яА-я]+)\]\*/) { "<b>#{$1}</b>" }
    text.gsub!(/\\\[([\wа-яА-Я]+)\]\\/) { "<i>#{$1}</i>" }
    text.gsub!(/\(\(([^\]]+) \[([^\]]+)\]\)\)/) { "<a href=#{$1}>#{$2}</a>" }
    text
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lists sites</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.slim
= render('shared/errors', resource: @page) if @page.errors.present?

= form_with model: @page, url: page_url, method: verb, data: { turbo:false } do |form|

  .title
  = form.label :title
  = form.text_field :title

  .name
  = form.label :name
  = form.text_field :name

  .content
  = form.label :content
  = form.text_area :content, size: "80x30"

  .submit
  = form.submit

app/views/pages/edit.html.slim
= render "form", verb: :patch, page_url: page_edit_path
= link_to "Back", root_path

app/views/pages/index.html.slim
body
  h1 Lists sites

  = render_tree(@root)

app/views/pages/new.html.slim
body
  h1 New root site

= render "form", verb: :post, page_url: pages_path

= link_to "Back", root_path

app/views/pages/show.html.slim
h3= @page.title

= sanitize normalizing_content(@page.content)
br
= link_to "Back", root_path

app/views/shared/_errors.html.slim
- resource.errors.full_messages.each do |message|
  li
    = message